### ISSUE TITLE
How to use this module on macOS

### ISSUE THREAD

**Issue by orklann** [nutti/fake-bpy-module#15]
Just copy the premade module to the python library folder, and `import bpy` and got following errors:

```
Python 2.7.10 (default, Aug 17 2018, 19:45:58)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/bpy/__init__.py", line 1, in <module>
    from . import types
  File "/Library/Python/2.7/site-packages/bpy/types.py", line 31
SyntaxError: Non-ASCII character '\xe2' in file /Library/Python/2.7/site-packages/bpy/types.py on line 32, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

Need your help.

As I can not import bpy, so that I can not use it's autocomplete function in Atom editor.

**Comment by orklann** [comment]
I just fixed this issue by adding one of the premade module path to `Extra Paths For Package` in `Autocomplete-python` settings.
