### ISSUE TITLE
Integration with PyCharm

### ISSUE THREAD

**Issue by mg-development** [nutti/fake-bpy-module#19]
* OS: Ubuntu 16.04
* Blender version: 2.80
(After execution: pip3.7 install fake-bpy-module-2.80)

When I try import bpy module in PyCharm I got:

Traceback (most recent call last):
  File "/home/michal/Programs/blender-2.80/2.80/scripts/addons/Test1.py", line 6, in <module>
    import bpy
  File "/usr/local/lib/python3.7/site-packages/bpy/__init__.py", line 3, in <module>
    from . import types
  File "/usr/local/lib/python3.7/site-packages/bpy/types.py", line 55744
    def prop_with_popover(self,
                         ^
SyntaxError: non-default argument follows default argument

If I correct these by (adding default argument) I got the next one:

Traceback (most recent call last):
  File "/home/michal/Programs/blender-2.80/2.80/scripts/addons/Test1.py", line 6, in <module>
    import bpy
  File "/usr/local/lib/python3.7/site-packages/bpy/__init__.py", line 3, in <module>
    from . import types
  File "/usr/local/lib/python3.7/site-packages/bpy/types.py", line 1737, in <module>
    class BlendData:
  File "/usr/local/lib/python3.7/site-packages/bpy/types.py", line 1980, in BlendData
    def batch_remove(self, ids=(id1, id2, ...)):
NameError: name 'id1' is not defined

Is it a version 'python vs blender' mismatch?

Regards,
Michal

**Comment by nutti** [comment]
Nice catch. Thanks.

They are bugs of fake-bpy-module.
I'm now tackling to fix them.

**Comment by nutti** [comment]
This bug is fixed and fixed patch is now in master branch.
