### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by preritj** [nutti/fake-bpy-module#20]
**System Information**
  
* OS: Mac
* Blender version: 2.80

**Expected behavior**  
Trying to import `bpy`

**Description about the bug**  
Getting this error:
```
>>> import bpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/bpy/__init__.py", line 3, in <module>
    from . import types
  File "/usr/local/lib/python3.6/site-packages/bpy/types.py", line 55744
    def prop_with_popover(self,
                         ^
SyntaxError: non-default argument follows default argument
```

**Comment by nutti** [comment]
Thanks, but this bug is same as #19 

So, I will close this. Please wait until the new modules are released.
