### ISSUE TITLE
`bpy.ops` still has `override_context` / positional arguments

### ISSUE THREAD

**Issue by Andrej730** [nutti/fake-bpy-module#321]
See snippet below - it fails if executed in the latest versions of Blender though typing still supports it.

```python
# Traceback (most recent call last):
#   File "\Blender\4.3\python\Lib\code.py", line 90, in runcode
#     exec(code, self.locals)
#   File "<blender_console>", line 1, in <module>
#   File "\Blender\4.3\scripts\modules\bpy\ops.py", line 106, in __call__
#     C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
#                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#   File "\Blender\4.3\scripts\modules\bpy\ops.py", line 60, in _parse_args
#     raise ValueError("1-2 args execution context is supported")
# ValueError: 1-2 args execution context is supported
bpy.ops.transform.translate({"active_object": bpy.data.objects["Cube"], "selected_objects": [bpy.data.objects["Cube"]]}, value=(-0, -11.4476, -0))
```

![image](https://github.com/user-attachments/assets/754a9ab2-c0d0-4b0c-802d-1e5a1017066d)

----

Also this kind of line has no typing errors - since `undo` and `execution_context` are not defined as positional-only arguments, though they are.
```python
# TypeError: Converting py args to operator properties: : keyword "undo" unrecognized
bpy.ops.transform.translate(undo=True)
```

**Comment by nutti** [comment]
This issue is now fixed.
